### ISSUE TITLE
still having an issue on OSX

### ISSUE THREAD

**Issue by jfroffice** [nidium/Nidium#7]
After the last fix on OSX, I am still having an error after running `./configure_frontend`
```
      std::__1::__tree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::destroy(std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*) in libicutu.a(udbgutil.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)", referenced from:
      KnownIssues::print() in libicutu.a(udbgutil.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()", referenced from:
      KnownIssues::print() in libicutu.a(udbgutil.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libicutu.a(udbgutil.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libicutu.a(udbgutil.o)
  "std::__1::cout", referenced from:
      KnownIssues::print() in libicutu.a(udbgutil.o)
  "std::__1::ctype<char>::id", referenced from:
      KnownIssues::print() in libicutu.a(udbgutil.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libicutu.a(udbgutil.o)
  "std::__1::locale::~locale()", referenced from:
      KnownIssues::print() in libicutu.a(udbgutil.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libicutu.a(udbgutil.o)
  "std::__1::ios_base::clear(unsigned int)", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libicutu.a(udbgutil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [icuinfo] Error 1
make[5]: *** [all-recursive] Error 2
make[4]: *** [all-recursive] Error 2
make[3]: *** [buildicu] Error 2
make[2]: *** [intl/icu/compile] Error 2
make[1]: *** [compile] Error 2
make: *** [default] Error 2
Failed to run previous command
```

Moreover, it would be more comfortable to have the option to force the download of all external dependencies than having to answer [Y/n] for each dependency.

**Comment by paraboul** [comment]
Looks like a libc++/ libstdc++ mixing issue.
Nicolas can you check?

**Comment by efyx** [comment]
My apologies for the late fix. This should be good now.

About the issue where the configure script is prompting you to download all external dependencies, could you update your NativeTools repository, it should be fixed now.

Thanks for testing :)

**Comment by jfroffice** [comment]
Thank you.

I encountered another issue.
```
[INFO  ] Bulding portaudio
[INFO  ] Executing ./configure --without-jack --without-asihpi --without-winapi
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking target system type... x86_64-apple-darwin15.6.0
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by clang... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin15.6.0 file names to x86_64-apple-darwin15.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking command to parse /usr/bin/nm -B output from clang object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... no
checking how to run the C preprocessor... clang -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if clang supports -fno-rtti -fno-exceptions... yes
checking for clang option to produce PIC... -fno-common -DPIC
checking if clang PIC flag -fno-common -DPIC works... yes
checking if clang static flag -static works... no
checking if clang supports -c -o file.o... yes
checking if clang supports -c -o file.o... (cached) yes
checking whether the clang linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... clang++ -E
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... no
checking for clang++ option to produce PIC...  -DPIC
checking if clang++ PIC flag  -DPIC works... yes
checking if clang++ static flag  works... yes
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... no
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for ar... /usr/bin/ar
checking whether byte ordering is bigendian... no
checking for snd_pcm_open in -lasound... no
checking sys/soundcard.h usability... no
checking sys/soundcard.h presence... no
checking for sys/soundcard.h... no
checking linux/soundcard.h usability... no
checking linux/soundcard.h presence... no
checking for linux/soundcard.h... no
checking machine/soundcard.h usability... no
checking machine/soundcard.h presence... no
checking for machine/soundcard.h... no
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking for clock_gettime in -lrt... no
checking for clock_gettime... no
checking for nanosleep... yes
configure: error: Couldn't find 10.5, 10.6, 10.7, 10.8 or 10.9 SDK
Failed to run previous command
```
But I am not sure that it is related to Nidium.

**Comment by efyx** [comment]
Which version of OSX are you running ? Can you try the following command and report the output : 
- `xcodebuild -version`
- `xcodebuild -version -showsdks`

**Comment by jfroffice** [comment]
```
$ xcodebuild -version
Xcode 8.0
Build version 8A218a
```
```
$ xcodebuild -version -showsdks
iOS SDKs:
	iOS 10.0                      	-sdk iphoneos10.0

iOS Simulator SDKs:
	Simulator - iOS 10.0          	-sdk iphonesimulator10.0

macOS SDKs:
	macOS 10.12                   	-sdk macosx10.12

tvOS SDKs:
	tvOS 10.0                     	-sdk appletvos10.0

tvOS Simulator SDKs:
	Simulator - tvOS 10.0         	-sdk appletvsimulator10.0

watchOS SDKs:
	watchOS 3.0                   	-sdk watchos3.0

watchOS Simulator SDKs:
	Simulator - watchOS 3.0       	-sdk watchsimulator3.0
```

**Comment by paraboul** [comment]
We need to support later osx sdk. I think we have to patch various deps configure files.

**Comment by efyx** [comment]
Yes indeed. @jfroffice please note that Nidium has not been built/tested against OSX 10.12 (yet) so you may experience other issues.

I have just commited a patch for portaudio, if you could try it : 
- Pull the latest master of Nidium
- Run `rm -rf third-party/.default/portaudio/`
- Run `./configure-frontend`

**Comment by jfroffice** [comment]
@efyx  thank you for your time.

I have the following issue after your fix.
```
Syncing projects: 100% ( 9/ 9) third_party/zlib

buildtools (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/buildtools.git /Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2' in '/Users/xxxxxx/Nidium/third-party/.default/angle'
[0:00:00] Cloning into '/Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2'...
[0:00:00] fatal: unable to access 'https://chromium.googlesource.com/chromium/buildtools.git/': Could not resolve host: chromium.googlesource.com

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/buildtools.git /Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2' in '/Users/xxxxxx/Nidium/third-party/.default/angle'
[0:00:00] Cloning into '/Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2'...
[0:00:00] fatal: unable to access 'https://chromium.googlesource.com/chromium/buildtools.git/': Could not resolve host: chromium.googlesource.com

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/buildtools.git /Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2' in '/Users/xxxxxx/Nidium/third-party/.default/angle'
[0:00:01] Cloning into '/Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2'...
[0:00:01] fatal: unable to access 'https://chromium.googlesource.com/chromium/buildtools.git/': Could not resolve host: chromium.googlesource.com

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/buildtools.git /Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2' in '/Users/xxxxxx/Nidium/third-party/.default/angle'
[0:00:03] Cloning into '/Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2'...
[0:00:03] fatal: unable to access 'https://chromium.googlesource.com/chromium/buildtools.git/': Could not resolve host: chromium.googlesource.com
Traceback (most recent call last):
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_scm.py", line 962, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_scm.py", line 1249, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_utils.py", line 293, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_utils.py", line 613, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/buildtools.git /Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2' returned non-zero exit status 128 in /Users/xxxxxx/Nidium/third-party/.default/angle
----------------------------------------
Traceback (most recent call last):
  File "/Users/xxxxxx/Nidium/third-party/depot_tools/gclient.py", line 2378, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/xxxxxx/Nidium/third-party/depot_tools/gclient.py", line 2364, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/xxxxxx/Nidium/third-party/depot_tools/gclient.py", line 2117, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/xxxxxx/Nidium/third-party/depot_tools/gclient.py", line 1568, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_utils.py", line 1112, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/xxxxxx/Nidium/third-party/depot_tools/gclient.py", line 867, in run
    file_list)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_scm.py", line 166, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_scm.py", line 450, in update
    self._Clone(revision, url, options)
  File "/Users/xxxxxx/Nidium/third-party/.default/depot_tools/gclient_scm.py", line 970, in _Clone
    if os.listdir(tmp_dir):
OSError: [Errno 2] No such file or directory: '/Users/xxxxxx/Nidium/third-party/.default/angle/_gclient_buildtools_WfXcR2'
Failed to run previous command
```

**Comment by efyx** [comment]
Hi, given the logs I believe it was because https://chromium.googlesource.com was unavailable. You could try again and it should work.

**Comment by jfroffice** [comment]
I retry and get this error
```
[INFO  ] Bulding ffmpeg
[INFO  ] Executing ./configure             --disable-vaapi --disable-avdevice --disable-postproc --disable-avfilter --disable-ffserver --disable-lzma --disable-bzlib             --enable-decoder=ac3,aac,mp3,vorbis,pcm_s16be_planar,pcm_s16le,pcm_s16le_planar,pcm_s24be,pcm_s24daud,pcm_s24le,pcm_s24le_planar,pcm_s32be,pcm_s32le,pcm_s32le_planar,pcm_s8,pcm_s8_planar,pcm_u16be,pcm_u16le,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,pcm_u8,h264,mpeg4,mpeg2video,wmv1,wmv2,wmv3,wmv3_crystalhd,wmv3_vdpau,wmv3image,wmalossless,wmapro,wmav1,wmav2,wmavoice,vc1,vc1_crystalhd,vc1_vdpau,vc1image            --enable-parser=vorbis,mpegaudio,mpegvideo,mpeg4video,h264,vp8,aac,vc1            --enable-demuxer=matroska,mp3,ogg,vorbis,pcm_alaw,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_mulaw,pcm_s16be,pcm_s16le,pcm_s24be,pcm_s24le,pcm_s32be,pcm_s32le,pcm_s8,pcm_u16be,pcm_u16le,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,pcm_u8,h264,mpegvideo,aac,mov,avi,wav,asf
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
Failed to run previous command
```

**Comment by efyx** [comment]
Hi, you need, to install "yasm" software, since you are on OSX you can use brew : `brew install yasm` should do the trick.

**Comment by paraboul** [comment]
We should ship a binary of yasm. Brew is not installed by default on osx.

**Comment by jfroffice** [comment]
works now.

+1 to ship a binary of __yasm__ as https://github.com/Eloston/ungoogled-chromium
